### ISSUE TITLE
Ajout de la fresque du sol

### ISSUE THREAD

**Issue by DesmoricFR** [Benbb96/liste-des-fresques#1]
Bonjour,
Pour contribuer à la liste, j'ai découvert il y a peu de temps l'existence de la fresque du sol, disponible depuis https://fresquedusol.com/

**Comment by Benbb96** [comment]
Bonjour @DesmoricFR,

Merci pour ta suggestion et la découverte de cette fresque qui semble très récente ! Je viens de l'ajouter à ma liste :wink:
