### ISSUE TITLE
Projets similaires

### ISSUE THREAD

**Issue by pinage404** [Benbb96/liste-des-fresques#2]
Salut,

Il serait peut etre bien de mentionner ces projets similaires :

https://wiki.climatefresk.org/?title=Les_fresques_amies	

https://github.com/trouver-une-fresque/trouver-une-fresque

**Comment by Benbb96** [comment]
Hello @pinage404, merci pour ta suggestion ! J'ai rajouté ces liens dans une section _Ressources_ en bas de page :wink:
