### ISSUE TITLE
Fresque De l'Orientation

### ISSUE THREAD

**Issue by FresqueOrientation** [Benbb96/liste-des-fresques#6]
Atelier collaboratif permettant une prise de recul individuelle et collective nécessaire à une réflexion sur l'orientation scolaire et professionnelle

**Comment by FresqueOrientation** [comment]
Comment ajouter une nouvelle fresque sur le tableur "Inventaire" ?

**Comment by Benbb96** [comment]
> Comment ajouter une nouvelle fresque sur le tableur "Inventaire" ?

Bonjour, je crois bien que vous pouvez directement remplir le tableur avec vos informations.

**Comment by FresqueOrientation** [comment]
Merci pour votre retour, 
Je l'ai fait mais elle a été supprimée, j'ai cru alors que cela devait passer par une demande.

**Comment by Benbb96** [comment]
Je vois pourtant bien la Fresque de l'Orientation ligne 156. Il y avait sûrement un filtre actif qui masquait les fresques en création.
