### ISSUE TITLE
Ajout Fresque de l'Orientation

### ISSUE THREAD

**Issue by FresqueOrientation** [Benbb96/liste-des-fresques#7]
Bonjour, j'aimerai ajouter la Fresque de l'Orientation, nous sommes en période de test avec les jeunes pour nous communiquerons bien plus une fois la version Beta terminée.
La Fresque de l'Orientation est un atelier collaboratif qui permet une prise de recul sur les étapes, les freins et les leviers liés au processus d'orientation.
fresquedelorientation@gmail.com
@ suivre
Merci pour ce beau travail
Thierry VERGER

**Comment by Benbb96** [comment]
Bonjour,

Je préfère ajouter sur ma liste seulement des fresques qui ont passé l'étape de test. Comme indiqué dans #6 vous devriez pouvoir remplir le tableur regroupant l'ensemble des fresques en précisant que la vôtre est encore en cours de construction.

Bonne continuation !
